### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Ludmilla-Oliveira---16-0013348#1]
- Sugere-se a segmentação dos objetivos em objetivos gerais e específicos
- Melhorar o texto dos requisitos de solução
- Pode-se complementar a finalidade colocando se o texto tem finalidade acadêmica ou de engenharia de campo.
- Colocar todas as hipóteses possíveis no item das hipóteses que podem ser feitas, e filtrá-las nas hipóteses que devem ser feitas.

**Comment by lud-oliv** [comment]
Atualizado no Read.me professor

**Comment by lgnsparda** [comment]
- Refazer a finalidade do projeto, falando se é acadêmica ou industrial
- Na figura esquemática da modelagem, sugere-se usar o diâmetro ao invés do raio.

**Comment by lud-oliv** [comment]
Pronto professor
