### ISSUE TITLE
Artigo

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Ludmilla-Oliveira---16-0013348#4]
- Refazer a estrutura do artigo na seguinte forma:
-resumo
-palavras-chave 
-introdução 
-materiais e métodos 
-resultados
-conclusões
- Não é preciso colocar as curvas de convergência
- A análise de resultados deve ser mais explorada. Observar o comportamento dos gráficos e explorar melhor a comparação com a teoria

**Comment by lud-oliv** [comment]
Professor, 
Passei meu projeto pra LaTeX, que fica melhor formatado 
O link pra acessar é 

https://www.overleaf.com/4191591417yggnsbtmymzm 

O artigo também está aqui
[Artigo___projeto_de_fluidos (1).pdf](https://github.com/Dinamica-dos-Fluidos-CFD/Ludmilla-Oliveira---16-0013348/files/4974643/Artigo___projeto_de_fluidos.1.pdf)

**Comment by lgnsparda** [comment]
- Não é preciso sumário no artigo.
- DESAFIO 2: Colocar o trabalho no formato de relatório técnico

**Comment by lud-oliv** [comment]
O link para acesso do relatório técnico 
https://www.overleaf.com/read/svvsgwjnzqzw

O arquivo do relatório é 
[Relat_rio_t_cnico (2).pdf](https://github.com/Dinamica-dos-Fluidos-CFD/Ludmilla-Oliveira---16-0013348/files/5007817/Relat_rio_t_cnico.2.pdf)
